### ISSUE TITLE
add support for isAcyclic

### ISSUE THREAD

**Issue by Viky-zhang** [graphp/algorithms#21] opened 2016-05-16 04:22 UTC
Add support for isAcyclic? 
not by TopologicalSort->getVertices() `Not a DAG`.

ref: https://github.com/cpettitt/graphlib/wiki/API-Reference#alg-is-acyclic

**Comment by clue** [comment] 2016-05-16 11:10
This is a duplicate of #2, PRs would be much appreciated! :+1:

**Closed by clue** 2016-05-16 11:10 UTC
